/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cliente;

import Fondos.FondoPanel;
import java.io.ObjectOutputStream;
import Modelos.Mensaje;
import Modelos.TipoMensaje;
import Sonidos.ReproductorAudio;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.net.URL;
import java.util.List;

/**
 *
 * @author jos_m
 */
public class PantallaLobby extends javax.swing.JFrame implements ReceptorMensajes {
    private String nombreJugador;
    private ReproductorAudio reproductor = new ReproductorAudio();
    private ObjectOutputStream salida;
    private ObjectInputStream entrada;
    private EscuchaServidorThread escucha;

    
    /**
     * Creates new form PantallaLobby
     */
    public PantallaLobby() {
        initComponents();
        this.setSize(1000, 520);           // tamaño inicial personalizado
        this.setLocationRelativeTo(null);  // centro de la pantalla
        
        // Crear el panel con imagen de fondo
        URL ruta = getClass().getResource("/Imagenes/fondoLobby.jpg");
        FondoPanel fondo = new FondoPanel(ruta);
        fondo.setOpaque(false);

        panelLobby.setLayout(new java.awt.BorderLayout());
        panelLobby.add(fondo, java.awt.BorderLayout.CENTER);

    // Enviar fondo al fondo
        panelLobby.setComponentZOrder(fondo, panelLobby.getComponentCount() - 1);
        setLocationRelativeTo(null);
        
        reproductor.reproducir("/Sonidos/musica.wav");
        areaChat.setEditable(false);
    }
    
    @Override
    public void dispose() {
        reproductor.detener(); // Detener la música antes de cerrar
        super.dispose();       // Cerrar la ventana normalmente
    }
    
    public void initData(String nombreJugador, ObjectOutputStream salida, ObjectInputStream entrada, EscuchaServidorThread escucha) {
        this.nombreJugador = nombreJugador;
        this.salida = salida;
        this.entrada = entrada;
        this.escucha = escucha;

        setTitle("Lobby de " + nombreJugador);
    }


    
    public void recibirMensaje(Mensaje mensaje) {
        areaChat.append(mensaje.getEnviador() + ": " + mensaje.getContenido().toString()     + "\n");
    }
    
    public void actualizarListaJugadores(List<String> jugadores) {
        comboReceptores.removeAllItems();
        comboReceptores.addItem("ALL"); // para mensajes públicos

        for (String jugador : jugadores) {
            if (!jugador.equals(nombreJugador)) {
                comboReceptores.addItem(jugador);
            }
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLobby = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaChat = new javax.swing.JTextArea();
        Desconectarse = new javax.swing.JButton();
        btnPublico = new javax.swing.JButton();
        txtPublico = new javax.swing.JTextField();
        btnSendPrivate = new javax.swing.JButton();
        lblPersona = new javax.swing.JLabel();
        lblDetalle = new javax.swing.JLabel();
        txtDetalle = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnPartida = new javax.swing.JButton();
        comboReceptores = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        areaChat.setColumns(20);
        areaChat.setRows(5);
        jScrollPane1.setViewportView(areaChat);

        Desconectarse.setFont(new java.awt.Font("SimSun-ExtG", 0, 12)); // NOI18N
        Desconectarse.setText("Desconectarse");

        btnPublico.setFont(new java.awt.Font("SimSun-ExtB", 0, 12)); // NOI18N
        btnPublico.setText("Enviar Mensaje Público");
        btnPublico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublicoActionPerformed(evt);
            }
        });

        txtPublico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPublicoActionPerformed(evt);
            }
        });

        btnSendPrivate.setFont(new java.awt.Font("SimSun-ExtB", 0, 12)); // NOI18N
        btnSendPrivate.setText("Enviar Mensaje Privado");
        btnSendPrivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendPrivateActionPerformed(evt);
            }
        });

        lblPersona.setFont(new java.awt.Font("SimSun-ExtB", 0, 12)); // NOI18N
        lblPersona.setForeground(new java.awt.Color(255, 255, 255));
        lblPersona.setText("Persona");

        lblDetalle.setFont(new java.awt.Font("SimSun-ExtB", 0, 12)); // NOI18N
        lblDetalle.setForeground(new java.awt.Color(255, 255, 255));
        lblDetalle.setText("Detalle:");

        txtDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDetalleActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Brush Script MT", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bienvenido al Lobby");

        btnPartida.setFont(new java.awt.Font("SimSun-ExtG", 0, 12)); // NOI18N
        btnPartida.setText("Ingresar al juego");
        btnPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartidaActionPerformed(evt);
            }
        });

        comboReceptores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboReceptores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboReceptoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLobbyLayout = new javax.swing.GroupLayout(panelLobby);
        panelLobby.setLayout(panelLobbyLayout);
        panelLobbyLayout.setHorizontalGroup(
            panelLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLobbyLayout.createSequentialGroup()
                .addGroup(panelLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLobbyLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40))
                    .addGroup(panelLobbyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLobbyLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Desconectarse)
                                .addGap(220, 220, 220))
                            .addGroup(panelLobbyLayout.createSequentialGroup()
                                .addGroup(panelLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSendPrivate)
                                    .addGroup(panelLobbyLayout.createSequentialGroup()
                                        .addComponent(btnPublico)
                                        .addGap(62, 62, 62)
                                        .addComponent(txtPublico, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelLobbyLayout.createSequentialGroup()
                                        .addGroup(panelLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDetalle)
                                            .addComponent(lblPersona))
                                        .addGap(48, 48, 48)
                                        .addGroup(panelLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(comboReceptores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(panelLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLobbyLayout.createSequentialGroup()
                        .addComponent(btnPartida)
                        .addGap(618, 618, 618))
                    .addGroup(panelLobbyLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(267, 267, 267))))
        );
        panelLobbyLayout.setVerticalGroup(
            panelLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLobbyLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLobbyLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(58, 58, 58)
                        .addGroup(panelLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPublico)
                            .addComponent(txtPublico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(panelLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboReceptores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPersona))
                        .addGap(18, 18, 18)
                        .addGroup(panelLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDetalle)
                            .addComponent(txtDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(btnSendPrivate))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(panelLobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Desconectarse)
                    .addComponent(btnPartida))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLobby, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLobby, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPublicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublicoActionPerformed
        String texto = txtPublico.getText().trim();
        if (!texto.isBlank()) {
            try {
                Mensaje mensaje = new Mensaje(nombreJugador, texto, "ALL", TipoMensaje.PUBLICO);
                salida.writeObject(mensaje); // Enviar al servidor
                txtPublico.setText("");
            } catch (IOException e) {
                areaChat.append("[Error] No se pudo enviar el mensaje\n");
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPublicoActionPerformed

    private void txtPublicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPublicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPublicoActionPerformed

    private void txtDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDetalleActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_txtDetalleActionPerformed

    private void btnSendPrivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendPrivateActionPerformed
        String texto = txtDetalle.getText().trim();
        String receptor = comboReceptores.getSelectedItem().toString();
        
        if (!texto.isBlank()){
            try {
                TipoMensaje tipo = receptor.equals("ALL") ? TipoMensaje.PUBLICO : TipoMensaje.PRIVADO;
                Mensaje mensaje = new Mensaje(nombreJugador, texto, receptor, tipo);
                salida.writeObject(mensaje);
                 if (tipo == TipoMensaje.PRIVADO) {
                    areaChat.append("[Privado a " + receptor + "] " + texto + "\n");
                }

                txtDetalle.setText(""); 
            } catch (IOException e) {
                areaChat.append("[Error] No se pudo enviar el mensaje\n");
            }
        }
        
    }//GEN-LAST:event_btnSendPrivateActionPerformed

    private void btnPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartidaActionPerformed
        ZonaJuego zona = new ZonaJuego();
        zona.initData(nombreJugador, salida, entrada);
        escucha.setReceptor(zona);

        zona.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPartidaActionPerformed

    private void comboReceptoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboReceptoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboReceptoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaLobby().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Desconectarse;
    private javax.swing.JTextArea areaChat;
    private javax.swing.JButton btnPartida;
    private javax.swing.JButton btnPublico;
    private javax.swing.JButton btnSendPrivate;
    private javax.swing.JComboBox<String> comboReceptores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDetalle;
    private javax.swing.JLabel lblPersona;
    private javax.swing.JPanel panelLobby;
    private javax.swing.JTextField txtDetalle;
    private javax.swing.JTextField txtPublico;
    // End of variables declaration//GEN-END:variables
}
