/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cliente;

import Mapas.Mapas;
import Mapas.cargarMapas;
import Personajes.Jugador;
import Modelos.Mensaje;
import Modelos.TipoMensaje;
import Sonidos.ReproductorAudio;
import java.awt.Dimension;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author jos_m
 */
public class ZonaJuego extends javax.swing.JFrame implements ReceptorMensajes {
    private String nombreJugador;
    private ReproductorAudio reproductor = new ReproductorAudio();
    private ObjectOutputStream salida;
    private ObjectInputStream entrada;
    private List<Jugador> jugadores = new ArrayList<>();
    /**
     * Creates new form ZonaJuego
     */
    public ZonaJuego() {
        initComponents();
        reproductor.reproducir("/Sonidos/musica.wav");
        txtSms.setEditable(false);
    }
    
    public void cargarPanelMapa() {
        char[][] mapa = cargarMapas.cargarMapaDesdeArchivo("mapa1.txt");
        Mapas panelMapa = new Mapas(mapa);

        // Asegurar tamaño del contenedor
        Dimension dim = panelMapa.getPreferredSize();
        jPanel1.setLayout(null);
        jPanel1.setPreferredSize(dim);
        jPanel1.setSize(dim);

        // Preparar y agregar
        panelMapa.setBounds(0, 0, dim.width, dim.height);
        panelMapa.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED, 2)); // debug visual

        jPanel1.removeAll();
        jPanel1.add(panelMapa);
        jPanel1.revalidate();
        jPanel1.repaint();
    }
    
    public void setJugadores(List<Jugador> jugadores) {
        this.jugadores = jugadores;
    }

    public void repaintMapa() {
        jPanel1.removeAll();
        jPanel1.setLayout(null);

        Mapas panelMapa = new Mapas(cargarMapas.cargarMapaDesdeArchivo("mapa1.txt"));
        panelMapa.setJugadores(jugadores); // 💡 este método lo vas a agregar en Mapas.java

        Dimension dim = panelMapa.getPreferredSize();
        panelMapa.setBounds(0, 0, dim.width, dim.height);

        jPanel1.add(panelMapa);
        jPanel1.revalidate();
        jPanel1.repaint();
        
        System.out.println("✅ Mapa repintado con " + jugadores.size() + " jugadores.");
    }


    
    public void initData(String nombreJugador, ObjectOutputStream salida, ObjectInputStream entrada) {
        this.nombreJugador = nombreJugador;
        this.salida = salida;
        this.entrada = entrada;

        setTitle("Zona de juego de " + nombreJugador);

        cargarPanelMapa();   // Cargar mapa con tamaño asegurado
        pack();              // Asegurar que el frame se ajuste al contenido
        setLocationRelativeTo(null); // Centrar
        setVisible(true);
      
    }
    
    public void dispose() {
        reproductor.detener(); // Detener la música antes de cerrar
        super.dispose();       // Cerrar la ventana normalmente
    }
    
    public void actualizarListaJugadores(List<String> jugadores) {
        System.out.println("🎯 Recibí jugadores: " + jugadores);
        comboElegir.removeAllItems();
        comboElegir.addItem("ALL"); // para mensajes públicos

        for (String jugador : jugadores) {
            if (!jugador.equals(nombreJugador)) {
                comboElegir.addItem(jugador);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSms = new javax.swing.JTextArea();
        btnEnviarPublico = new javax.swing.JButton();
        txtPublico = new javax.swing.JTextField();
        comboElegir = new javax.swing.JComboBox<>();
        btnEnviarPrivado = new javax.swing.JButton();
        txtPrivado = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 344, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );

        txtSms.setColumns(20);
        txtSms.setRows(5);
        jScrollPane1.setViewportView(txtSms);

        btnEnviarPublico.setText("Enviar Mensaje Público");
        btnEnviarPublico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarPublicoActionPerformed(evt);
            }
        });

        comboElegir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboElegirActionPerformed(evt);
            }
        });

        btnEnviarPrivado.setText("Enviar Mensaje Privado");
        btnEnviarPrivado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarPrivadoActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");

        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnEnviarPublico, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtPublico, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(comboElegir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnEnviarPrivado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtPrivado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnSalir, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(comboElegir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEnviarPrivado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPrivado))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(btnSalir)
                        .addGap(80, 80, 80)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(txtPublico))
                    .addComponent(btnEnviarPublico))
                .addGap(25, 25, 25))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(btnSalir)
                                .addGap(18, 18, 18)
                                .addComponent(comboElegir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)))
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrivado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPublico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEnviarPrivado)
                            .addComponent(btnEnviarPublico))))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarPublicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarPublicoActionPerformed
        String texto = txtPublico.getText().trim();
        if (!texto.isBlank()) {
            try {
                Mensaje mensaje = new Mensaje(nombreJugador, texto, "ALL", TipoMensaje.PUBLICO);
                salida.writeObject(mensaje);
                txtSms.append(nombreJugador + ": " + texto + "\n");
                txtPublico.setText("");
            } catch (IOException e) {
                txtSms.append("[Error] No se pudo enviar el mensaje público\n");
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarPublicoActionPerformed

    private void btnEnviarPrivadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarPrivadoActionPerformed
        String texto = txtPrivado.getText().trim();
        String receptor = comboElegir.getSelectedItem().toString();

        if (!texto.isBlank() && receptor != null) {
            try {
                TipoMensaje tipo = receptor.equals("ALL") ? TipoMensaje.PUBLICO : TipoMensaje.PRIVADO;
                Mensaje mensaje = new Mensaje(nombreJugador, texto, receptor, tipo);
                salida.writeObject(mensaje);

                if (tipo == TipoMensaje.PRIVADO) {
                    txtSms.append("[Privado a " + receptor + "] " + texto + "\n");
                } else {
                    txtSms.append(nombreJugador + ": " + texto + "\n");
                }
                txtPrivado.setText("");
            } catch (IOException e) {
                txtSms.append("[Error] No se pudo enviar el mensaje privado\n");
            }
        }
    }//GEN-LAST:event_btnEnviarPrivadoActionPerformed

    private void comboElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboElegirActionPerformed
        
            // TODO add your handling code here:
    }//GEN-LAST:event_comboElegirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZonaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZonaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZonaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZonaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZonaJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarPrivado;
    private javax.swing.JButton btnEnviarPublico;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> comboElegir;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtPrivado;
    private javax.swing.JTextField txtPublico;
    private javax.swing.JTextArea txtSms;
    // End of variables declaration//GEN-END:variables

    @Override
    public void recibirMensaje(Mensaje mensaje) {
        txtSms.append(mensaje.getEnviador() + ": " + mensaje.getContenido().toString()     + "\n");
    }
    
    
}
    

